- hosts: all
  tasks:
    - name: Clone repository
      command: git clone https://github.com/SamuelPerezJimenez/Segundo-parcial-algoritmos-paralelos

    - name: Change directory
      command: ls
      args:
        chdir: "Segundo-parcial-algoritmos-paralelos"

    - name: test
      command: mkdir conzao

    - name: ejecutar compose
      command: docker-compose build

    - name: ejecutar up
      command: docker-compose up

  become: true
