- hosts: all
  tasks:
    - name: Clone repository
      command: git clone https://github.com/SamuelPerezJimenez/Segundo-parcial-algoritmos-paralelos

    - name: ejecutar compose
      shell: "docker-compose build"
      args:
        chdir: "Segundo-parcial-algoritmos-paralelos"

    - name: ejecutar up
      command: docker-compose up

  become: true
