- hosts: all
  tasks:
    - name: remove
      command: rm -r Segundo-parcial-algoritmos-paralelos

    - name: Clone repository
      command: git clone https://github.com/SamuelPerezJimenez/Segundo-parcial-algoritmos-paralelos

    - name: Change directory
      args:
        chdir: "Segundo-parcial-algoritmos-paralelos"

    - name: ejecutar compose
      command: docker-compose up -d --build

  become: true
