- hosts: all
  tasks:
    - name: remove
      command: rm -r SamuelPerezJimenez/Segundo-parcial-algoritmos-paralelos

    - name: Clone repository
      command: git clone https://github.com/SamuelPerezJimenez/Segundo-parcial-algoritmos-paralelos

    - name: ls
      command: ls > touch ls.txt

  become: true
